version: 2
jobs:
  build:
    docker:
      image: circleci/python:3.8

    working_directory: ~/FlaskCI

    steps:
      - checkout
      - run: python -m venv venv
      - run: source venv/bin/activate
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pytest

